### ISSUE TITLE
请问楼主关于报错的一个问题，望解答，谢谢！

### ISSUE THREAD

**Issue by cantianaishu** [Pyjacc/Relation_ner_extraction_mrc1#1]
问题如下
 

 File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked

ModuleNotFoundError: No module named 'keras.api'

**Comment by cantianaishu** [comment]
应该是第86行 # 派生为带分段线性学习率的优化器。这一段代码我这边出了问题

**Comment by Pyjacc** [comment]
你好，谢谢关注，请你现在问题解决了吗？
















在 2022-05-14 17:11:55，"cantianaishu" ***@***.***> 写道：

应该是第86行 # 派生为带分段线性学习率的优化器。这一段代码我这边出了问题

**Comment by cantianaishu** [comment]
好的谢谢您的回复，我自己再好好试试
